# ABOUT TO BREAK RANGE DETECTOR - CONFIGURATION

# PERMANENT MANDATED 25-COIN WATCHLIST
# DO NOT ADD, REMOVE, SUBSTITUTE, OR ALPHABETIZE
DEFAULT_WATCHLIST = [
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "PEPEUSDT",
    "BONKUSDT",
    "SHIBUSDT",
    "USELESSUSDT",
    "SPACEUSDT",
    "MOVEUSDT",
    "ZECUSDT",
    "SPXUSDT",
    "PEOPLEUSDT",
    "PENGUUSDT",
    "FARTCOINUSDT",
    "LINEAUSDT",
    "MEMEUSDT",
    "PUMPUSDT",
    "AIXBTUSDT",
    "BRETTUSDT",
    "FOGOUSDT",
    "GOOGLUSDT",
    "FLOKIUSDT",
    "IWMUSDT",
    "MOODENGUSDT",
    "NEARUSDT"
]

WATCHLIST = DEFAULT_WATCHLIST

# Preferred monitoring timeframes
TIMEFRAMES = ["3M", "5M", "15M", "1H", "4H"]

# Detector Parameters
SMA_FAST = 20
SMA_SLOW = 200
READINESS_THRESHOLD = 20
